# Generated by Django 6.0 on 2026-01-19 21:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Condition name (e.g., Pyelonephritis)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional description of the condition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EMRSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pathogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pathogen name (e.g., E. coli)', max_length=100, unique=True)),
                ('gram_type', models.CharField(blank=True, choices=[('positive', 'Gram Positive'), ('negative', 'Gram Negative'), ('other', 'Other')], help_text='Gram staining classification', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional pathogen information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pathogens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_no', models.IntegerField(blank=True, help_text='Case number from CSV', null=True)),
                ('name', models.CharField(help_text='Patient name', max_length=255)),
                ('date_recorded', models.DateField(help_text='Date when patient data was recorded')),
                ('age', models.PositiveIntegerField(help_text='Patient age', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Patient gender', max_length=1, null=True)),
                ('admission', models.IntegerField(choices=[(0, 'Outpatient'), (1, 'Inpatient')], default=1, help_text='Admission type: 0=Outpatient, 1=Inpatient')),
                ('body_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg (required for antibiotic dosing)', max_digits=6)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm (optional)', max_digits=6, null=True)),
                ('diagnosis1', models.CharField(help_text='Primary diagnosis (required)', max_length=255)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Celsius', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(50)])),
                ('scr', models.DecimalField(decimal_places=2, help_text='Serum Creatinine (mg/dL) - required for dosing', max_digits=5)),
                ('cockcroft_gault_crcl', models.DecimalField(decimal_places=2, help_text='Creatinine Clearance (mL/min) - required for dosing', max_digits=12)),
                ('wbc', models.DecimalField(blank=True, decimal_places=2, help_text='White Blood Cell count', max_digits=10, null=True)),
                ('crp', models.DecimalField(blank=True, decimal_places=2, help_text='C-reactive Protein (mg/L)', max_digits=8, null=True)),
                ('hb', models.DecimalField(blank=True, decimal_places=1, help_text='Hemoglobin level (g/dL)', max_digits=5, null=True)),
                ('platelet', models.DecimalField(blank=True, decimal_places=0, help_text='Platelet count', max_digits=10, null=True)),
                ('ast', models.DecimalField(blank=True, decimal_places=1, help_text='AST (IU/L)', max_digits=6, null=True)),
                ('alt', models.DecimalField(blank=True, decimal_places=1, help_text='ALT (IU/L)', max_digits=6, null=True)),
                ('pathogen', models.CharField(blank=True, default='Unknown', help_text="Identified pathogen (use 'Unknown' if not identified)", max_length=500)),
                ('antibiogram', models.TextField(blank=True, help_text='Antibiogram/sensitivity test results', null=True)),
                ('sample_type', models.CharField(blank=True, default='Not specified', help_text='Sample type (blood, urine, sputum, etc.)', max_length=100)),
                ('antibiotics', models.CharField(blank=True, default='None', help_text='Primary antibiotic treatment', max_length=500)),
                ('antibiotics2', models.TextField(blank=True, help_text='Secondary/alternative antibiotic recommendations', null=True)),
                ('allergies', models.CharField(blank=True, default='None', help_text='Patient allergies', max_length=500)),
                ('diagnosis2', models.CharField(blank=True, help_text='Secondary diagnosis', max_length=255, null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Other current medications', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-date_recorded', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EMRSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('PO', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOP', 'Topical')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_antibiotic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
            options={
                'db_table': 'medications',
            },
        ),
        migrations.CreateModel(
            name='EMROrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('medication', 'Medication'), ('lab', 'Laboratory'), ('imaging', 'Imaging'), ('consult', 'Consultation')], max_length=20)),
                ('medication_name', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to EMR'), ('acknowledged', 'Acknowledged by EMR'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_emr_at', models.DateTimeField(blank=True, null=True)),
                ('emr_order_id', models.CharField(blank=True, max_length=100)),
                ('emr_response', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emr_orders', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CultureTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('sample_type', models.CharField(max_length=100)),
                ('pathogen', models.CharField(max_length=255)),
                ('sensitivity_results', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_tests', to='patients.patient')),
            ],
            options={
                'db_table': 'culture_tests',
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text="Severity description (e.g., 'Uncomplicated, community-acquired, mild to moderate')", max_length=200)),
                ('severity_order', models.PositiveIntegerField(default=1, help_text='Order for severity ranking (1=mild, 5=severe)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='severities', to='patients.condition')),
            ],
            options={
                'db_table': 'severities',
                'ordering': ['condition', 'severity_order'],
                'unique_together': {('condition', 'level')},
            },
        ),
        migrations.CreateModel(
            name='AntibioticDosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibiotic', models.CharField(help_text='Antibiotic name', max_length=100)),
                ('crcl_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum CrCl (mL/min)', max_digits=6, null=True)),
                ('crcl_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum CrCl (mL/min)', max_digits=6, null=True)),
                ('dialysis_type', models.CharField(choices=[('none', 'None'), ('hd', 'Hemodialysis'), ('pd', 'Peritoneal Dialysis'), ('crrt', 'CRRT'), ('ecmo', 'ECMO')], default='none', max_length=10)),
                ('dose', models.CharField(help_text="Dose (e.g., '500mg', '1-2g')", max_length=200)),
                ('route', models.JSONField(default=list, help_text="Administration routes (e.g., ['PO', 'IV'])")),
                ('interval', models.CharField(help_text="Dosing interval (e.g., 'q12h', 'q8h')", max_length=50)),
                ('duration', models.CharField(blank=True, help_text="Treatment duration (e.g., '7d', '10-14d')", max_length=50)),
                ('remark', models.TextField(blank=True, help_text='Additional dosing remarks or considerations')),
                ('patient_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosing_guidelines', to='patients.condition')),
                ('pathogens', models.ManyToManyField(help_text='Target pathogens', related_name='dosing_guidelines', to='patients.pathogen')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosing_guidelines', to='patients.severity')),
            ],
            options={
                'db_table': 'antibiotic_dosing',
                'ordering': ['antibiotic', 'condition', 'severity__severity_order'],
            },
        ),
        migrations.CreateModel(
            name='SeverityPathogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevalence', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare')], default='common', help_text='Prevalence of this pathogen in this severity', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='severities', to='patients.pathogen')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathogens', to='patients.severity')),
            ],
            options={
                'db_table': 'severity_pathogens',
                'unique_together': {('severity', 'pathogen')},
            },
        ),
    ]
