# Generated by Django 5.2.5 on 2025-08-21 23:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateField()),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('body_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in Celsius', max_digits=4, null=True)),
                ('diagnosis1', models.CharField(max_length=255)),
                ('diagnosis2', models.CharField(blank=True, max_length=255, null=True)),
                ('wbc', models.DecimalField(decimal_places=2, help_text='White Blood Cell count', max_digits=10)),
                ('hb', models.DecimalField(decimal_places=2, help_text='Hemoglobin level', max_digits=5)),
                ('platelet', models.DecimalField(decimal_places=0, help_text='Platelet count', max_digits=10)),
                ('ast', models.DecimalField(decimal_places=2, help_text='Aspartate Aminotransferase (IU/L)', max_digits=6)),
                ('alt', models.DecimalField(decimal_places=2, help_text='Alanine Aminotransferase (IU/L)', max_digits=6)),
                ('scr', models.DecimalField(decimal_places=2, help_text='Serum Creatinine (mg/dL)', max_digits=5)),
                ('cockcroft_gault_crcl', models.DecimalField(decimal_places=7, help_text='Cockcroft-Gault Creatinine Clearance', max_digits=10)),
                ('crp', models.DecimalField(decimal_places=2, help_text='C-reactive Protein (mg/L)', max_digits=8)),
                ('bun', models.DecimalField(blank=True, decimal_places=2, help_text='Blood Urea Nitrogen', max_digits=6, null=True)),
                ('gfr', models.DecimalField(blank=True, decimal_places=2, help_text='Glomerular Filtration Rate', max_digits=6, null=True)),
                ('pathogen', models.CharField(help_text='Identified pathogen', max_length=255)),
                ('sample_type', models.CharField(help_text='Sample type (e.g., urine, blood)', max_length=100)),
                ('current_medications', models.TextField(blank=True, help_text='List of current medications', null=True)),
                ('antibiotics', models.CharField(help_text='Current antibiotic treatment', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-date_recorded', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('PO', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOP', 'Topical')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_antibiotic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
            options={
                'db_table': 'medications',
            },
        ),
        migrations.CreateModel(
            name='CultureTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('sample_type', models.CharField(max_length=100)),
                ('pathogen', models.CharField(max_length=255)),
                ('sensitivity_results', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_tests', to='patients.patient')),
            ],
            options={
                'db_table': 'culture_tests',
            },
        ),
    ]
