# Generated by Django 5.2.5 on 2025-08-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='Penicillin', help_text='Patient allergies', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Kim', max_length=255),
        ),
    ]
