# Generated by Django 5.2.5 on 2025-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_allergies_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bun',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gfr',
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='None', help_text='Patient allergies', max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kg (BW)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cockcroft_gault_crcl',
            field=models.DecimalField(decimal_places=8, help_text='Cockcroft-Gault Creatinine Clearance', max_digits=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis1',
            field=models.CharField(help_text='Primary diagnosis', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis2',
            field=models.CharField(blank=True, help_text='Secondary diagnosis', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hb',
            field=models.DecimalField(decimal_places=2, help_text='Hemoglobin level (Hb)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, default='Patient', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pathogen',
            field=models.CharField(help_text='Identified pathogen', max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='platelet',
            field=models.DecimalField(decimal_places=0, help_text='Platelet count (PLT)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sample_type',
            field=models.CharField(help_text='Sample type (e.g., urine, blood, sputum)', max_length=100),
        ),
    ]
