# Generated by Django 5.2.5 on 2025-08-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_emrsystem_emrorder_emrsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntibioticDosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibiotic', models.CharField(max_length=100)),
                ('crcl_range', models.CharField(max_length=20)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, max_length=10)),
                ('interval', models.CharField(blank=True, max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('pathogen_effectiveness', models.JSONField(blank=True, default=list)),
                ('infection_types', models.JSONField(blank=True, default=list)),
                ('contraindications', models.JSONField(blank=True, default=list)),
                ('severity_score', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('antibiotic', 'crcl_range')},
            },
        ),
    ]
