# Generated by Django 5.2.5 on 2025-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_antibioticdosing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticdosing',
            name='crcl_range',
            field=models.CharField(max_length=50),
        ),
    ]
