# Generated by Django 5.2.5 on 2025-08-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_antibioticdosing_crcl_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticdosing',
            name='dose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='antibioticdosing',
            name='interval',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
