# Generated by Django 5.2.5 on 2025-08-27 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_antibioticdosing_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(help_text='Patient age', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(blank=True, default='None', help_text='Patient allergies', max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alt',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='ALT (IU/L)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='antibiotics',
            field=models.CharField(blank=True, default='None', help_text='Current antibiotic treatment', max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ast',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='AST (IU/L)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_temperature',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Temperature in Celsius', max_digits=4, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(50)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kg (required for antibiotic dosing)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cockcroft_gault_crcl',
            field=models.DecimalField(decimal_places=2, help_text='Creatinine Clearance (mL/min) - required for dosing', max_digits=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='crp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='C-reactive Protein (mg/L)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Other current medications', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_recorded',
            field=models.DateField(help_text='Date when patient data was recorded'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis1',
            field=models.CharField(help_text='Primary diagnosis (required)', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Patient gender', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hb',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hemoglobin level (g/dL)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm (optional)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(help_text='Patient name', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pathogen',
            field=models.CharField(blank=True, default='Unknown', help_text="Identified pathogen (use 'Unknown' if not identified)", max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='platelet',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Platelet count', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sample_type',
            field=models.CharField(blank=True, default='Not specified', help_text='Sample type (blood, urine, sputum, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='scr',
            field=models.DecimalField(decimal_places=2, help_text='Serum Creatinine (mg/dL) - required for dosing', max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='wbc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='White Blood Cell count', max_digits=10, null=True),
        ),
    ]
