# Generated by Django 5.2.5 on 2025-08-27 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patient_age_alter_patient_allergies_and_more'),
    ]

    operations = [
        # First, delete the old AntibioticDosing table
        migrations.RunSQL("DROP TABLE IF EXISTS patients_antibioticdosing;"),
        
        # Create new models
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Condition name (e.g., Pyelonephritis)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional description of the condition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pathogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pathogen name (e.g., E. coli)', max_length=100, unique=True)),
                ('gram_type', models.CharField(blank=True, choices=[('positive', 'Gram Positive'), ('negative', 'Gram Negative'), ('other', 'Other')], help_text='Gram staining classification', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional pathogen information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pathogens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text="Severity description (e.g., 'Uncomplicated, community-acquired, mild to moderate')", max_length=200)),
                ('severity_order', models.PositiveIntegerField(default=1, help_text='Order for severity ranking (1=mild, 5=severe)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='severities', to='patients.condition')),
            ],
            options={
                'db_table': 'severities',
                'ordering': ['condition', 'severity_order'],
                'unique_together': {('condition', 'level')},
            },
        ),
        migrations.CreateModel(
            name='SeverityPathogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevalence', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare')], default='common', help_text='Prevalence of this pathogen in this severity', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='severities', to='patients.pathogen')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathogens', to='patients.severity')),
            ],
            options={
                'db_table': 'severity_pathogens',
                'unique_together': {('severity', 'pathogen')},
            },
        ),
        # Create the new AntibioticDosing model
        migrations.CreateModel(
            name='AntibioticDosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibiotic', models.CharField(help_text='Antibiotic name', max_length=100)),
                ('crcl_min', models.DecimalField(decimal_places=2, help_text='Minimum CrCl (mL/min)', max_digits=6)),
                ('crcl_max', models.DecimalField(decimal_places=2, help_text='Maximum CrCl (mL/min)', max_digits=6)),
                ('dialysis_type', models.CharField(choices=[('none', 'None'), ('hd', 'Hemodialysis'), ('pd', 'Peritoneal Dialysis'), ('crrt', 'CRRT'), ('ecmo', 'ECMO')], default='none', max_length=10)),
                ('dose', models.CharField(help_text="Dose (e.g., '500mg', '1-2g')", max_length=200)),
                ('route', models.CharField(choices=[('PO', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous')], help_text='Administration route', max_length=10)),
                ('interval', models.CharField(help_text="Dosing interval (e.g., 'q12h', 'q8h')", max_length=50)),
                ('remark', models.TextField(blank=True, help_text='Additional dosing remarks or considerations')),
                ('patient_type', models.CharField(choices=[('adult', 'Adult'), ('pediatric', 'Pediatric'), ('elderly', 'Elderly'), ('pregnant', 'Pregnant')], default='adult', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosing_guidelines', to='patients.condition')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosing_guidelines', to='patients.severity')),
                ('pathogens', models.ManyToManyField(help_text='Target pathogens', related_name='dosing_guidelines', to='patients.pathogen')),
            ],
            options={
                'db_table': 'antibiotic_dosing',
                'ordering': ['antibiotic', 'condition', 'severity__severity_order'],
                'unique_together': {('antibiotic', 'condition', 'severity', 'crcl_min', 'crcl_max', 'dialysis_type', 'patient_type')},
            },
        ),
    ]
