# Generated by Django 5.2.5 on 2025-08-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20250827_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticdosing',
            name='patient_type',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=20),
        ),
    ]
