# Generated by Django 5.2.5 on 2025-08-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_antibioticdosing_patient_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antibioticdosing',
            options={'ordering': ['antibiotic', 'condition', 'severity__severity_order', 'route']},
        ),
        migrations.AlterUniqueTogether(
            name='antibioticdosing',
            unique_together={('antibiotic', 'condition', 'severity', 'crcl_min', 'crcl_max', 'dialysis_type', 'patient_type', 'route')},
        ),
    ]
