# Generated by Django 5.2.5 on 2025-08-27 14:21

from django.db import migrations, models
import json


def convert_route_to_json(apps, schema_editor):
    """Convert existing route CharField values to JSON list format"""
    AntibioticDosing = apps.get_model('patients', 'AntibioticDosing')
    
    for dosing in AntibioticDosing.objects.all():
        # Convert single route string to list of routes
        if dosing.route:
            # Create a list with the current route
            route_list = [dosing.route]
            dosing.route_json = json.dumps(route_list)
        else:
            dosing.route_json = json.dumps([])
        dosing.save()


def convert_route_to_string(apps, schema_editor):
    """Reverse conversion for rollback"""
    AntibioticDosing = apps.get_model('patients', 'AntibioticDosing')
    
    for dosing in AntibioticDosing.objects.all():
        if dosing.route_json:
            route_list = json.loads(dosing.route_json)
            if route_list:
                dosing.route = route_list[0]  # Take first route
            else:
                dosing.route = ''
        dosing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_antibioticdosing_options_and_more'),
    ]

    operations = [
        # Add temporary JSON field
        migrations.AddField(
            model_name='antibioticdosing',
            name='route_json',
            field=models.TextField(blank=True, null=True),
        ),
        
        # Convert data
        migrations.RunPython(convert_route_to_json, convert_route_to_string),
        
        # Remove old route field
        migrations.RemoveField(
            model_name='antibioticdosing',
            name='route',
        ),
        
        # Rename route_json to route and change to JSONField
        migrations.RenameField(
            model_name='antibioticdosing',
            old_name='route_json',
            new_name='route',
        ),
        
        # Change the field type to JSONField
        migrations.AlterField(
            model_name='antibioticdosing',
            name='route',
            field=models.JSONField(default=list, help_text="Administration routes (e.g., ['PO', 'IV'])"),
        ),
        
        # Update Meta options
        migrations.AlterModelOptions(
            name='antibioticdosing',
            options={'ordering': ['antibiotic', 'condition', 'severity__severity_order']},
        ),
        
        # Update unique_together
        migrations.AlterUniqueTogether(
            name='antibioticdosing',
            unique_together={('antibiotic', 'condition', 'severity', 'crcl_min', 'crcl_max', 'dialysis_type', 'patient_type')},
        ),
    ]
