# Generated by Django 5.2.5 on 2025-08-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_antibioticdosing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antibioticdosing',
            options={'ordering': ['antibiotic', 'condition', 'severity__severity_order']},
        ),
        migrations.AlterUniqueTogether(
            name='antibioticdosing',
            unique_together={('antibiotic', 'condition', 'severity', 'crcl_min', 'crcl_max', 'dialysis_type', 'patient_type')},
        ),
        migrations.AlterField(
            model_name='antibioticdosing',
            name='route',
            field=models.JSONField(default=list, help_text="Administration routes (e.g., ['PO', 'IV'])"),
        ),
    ]
