# Generated by Django 5.2.5 on 2025-08-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_antibioticdosing_options_and_more'),
        ('patients', '0012_auto_20250827_1721'),
    ]

    operations = [
    ]
