# Generated by Django 5.2.5 on 2025-08-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_merge_20250827_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibioticdosing',
            name='duration',
            field=models.CharField(blank=True, help_text="Treatment duration (e.g., '7d', '10-14d')", max_length=50),
        ),
    ]
