# Generated by Django 5.2.5 on 2025-08-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_antibioticdosing_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='antibioticdosing',
            unique_together={('antibiotic', 'condition', 'severity', 'crcl_min', 'crcl_max', 'dialysis_type', 'patient_type', 'dose', 'interval')},
        ),
    ]
