# Generated by Django 5.2.5 on 2025-08-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_antibioticdosing_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='antibioticdosing',
            unique_together=set(),
        ),
    ]
