# Generated by Django 5.2.5 on 2025-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_alter_antibioticdosing_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticdosing',
            name='crcl_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum CrCl (mL/min)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='antibioticdosing',
            name='crcl_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum CrCl (mL/min)', max_digits=6, null=True),
        ),
    ]
