# Generated by Django 6.0 on 2026-01-19 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_alter_antibioticdosing_crcl_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admission',
            field=models.IntegerField(choices=[(0, 'Outpatient'), (1, 'Inpatient')], default=1, help_text='Admission type: 0=Outpatient, 1=Inpatient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='antibiogram',
            field=models.TextField(blank=True, help_text='Antibiogram/sensitivity test results', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='antibiotics2',
            field=models.TextField(blank=True, help_text='Secondary/alternative antibiotic recommendations', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='case_no',
            field=models.IntegerField(blank=True, help_text='Case number from CSV', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='antibiotics',
            field=models.CharField(blank=True, default='None', help_text='Primary antibiotic treatment', max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Celsius', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
